apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: php-app

  template:
    metadata:
      labels:
        app: php-app

    spec:
      containers:
        - name: php-app

          image: "{{ .Values.php.repository }}:{{ .Values.php.tag }}"

          ports:
            - containerPort: 80

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME

            - name: DB_USER
              value: {{ .Values.mysql.username }}

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

